name: 'pr-comment'
description: 'Add PR changes and comments'
author: Shamnad

# Define your inputs here.
inputs:
  owner:
    description: 'The owner of the repo'
    required: true
  repo:
    description: 'The name of the repo'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true

runs:
  using: node24
  main: dist/index.js
